language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - cd tests
  - python -m unittest
  - cd ..

deploy:
  provider: pypi
  username: __token__
  password: $PYPI_TOKEN
  distributions: sdist bdist_wheel